"""add abs_item_id to books

Revision ID: 39c3dabab719
Revises: 409b732a22f6
Create Date: 2026-07-05 21:24:57.294617
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '39c3dabab719'
down_revision = '409b732a22f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abs_item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('abs_item_id')

    # ### end Alembic commands ###
