"""initial schema

Revision ID: 409b732a22f6
Revises: 
Create Date: 2026-07-05 19:14:41.065567
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '409b732a22f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=False)

    op.create_table('app_settings',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audible_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marketplace', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_owner_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('unlinked', 'linking', 'linked', 'needs_reauth', 'error', name='accountstatus'), nullable=False),
    sa.Column('badge_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_auth_blob', sa.Text(), nullable=True),
    sa.Column('encrypted_activation_bytes', sa.Text(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_log_ts'), ['ts'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audible_account_id', sa.Integer(), nullable=False),
    sa.Column('asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subtitle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authors', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('narrators', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('series_sequence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('cover_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('is_aax_available', sa.Boolean(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audible_account_id'], ['audible_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_asin'), ['asin'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_audible_account_id'), ['audible_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_excluded'), ['excluded'], unique=False)

    op.create_table('library_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('root_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audio_format', sa.Enum('m4b', 'mp3', 'opus', name='audioformat'), nullable=False),
    sa.Column('embed_cover', sa.Boolean(), nullable=False),
    sa.Column('embed_chapters', sa.Boolean(), nullable=False),
    sa.Column('audible_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audible_account_id'], ['audible_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'queued', 'downloading', 'downloaded', 'decrypting', 'tagging', 'moving', 'completed', 'failed', 'excluded', 'cancelled', name='jobstate'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bytes_total', sa.Integer(), nullable=True),
    sa.Column('bytes_done', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('library_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['library_profile_id'], ['library_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_jobs_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_jobs_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_download_jobs_book_id'))

    op.drop_table('download_jobs')
    op.drop_table('library_profiles')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_excluded'))
        batch_op.drop_index(batch_op.f('ix_books_audible_account_id'))
        batch_op.drop_index(batch_op.f('ix_books_asin'))

    op.drop_table('books')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_log_ts'))

    op.drop_table('event_log')
    op.drop_table('audible_accounts')
    op.drop_table('app_settings')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
