"""add totp 2fa to users

Revision ID: a0c35e89e04f
Revises: 39c3dabab719
Create Date: 2026-07-06 07:09:28.134145
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'a0c35e89e04f'
down_revision = '39c3dabab719'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('totp_recovery_codes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_recovery_codes')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
